### ISSUE TITLE
ModelCollection loading state regression

### ISSUE THREAD

**Issue by aron** [dropbox/pilot#23] opened 2017-03-07 10:35 UTC
The change to when the CurrentCollection state was updated in #19 causes issues with changes to state in the underlying ModelCollection. Especially when going from `notLoaded` to `loading(_)` for example.

The CurrentCollection state is now updated in a commit closure however it's not guaranteed this closure will be called, which means sometimes state changes are swallowed. For example in:

```
let (updates, commitCollectionChanges) = currentCollection.beginUpdate(underlyingCollection)
guard updates.hasUpdates else {
  // still synced
  // no need to update lastKnownCollectionViewContents
  return
}
```

https://github.com/dropbox/pilot/blob/73b750ca5d61fa7fc8f26a40555902125b673370/UI/Source/CollectionViews/CollectionViewModelDataSource.swift#L460-L465

In this case a ModelCollection going from `notLoaded` to `loading` will have no updates and so the underlying state will never be updated and the CollectionViewController won't display a loading spinner.

**Comment by wkiefer** [comment] 2017-03-07 17:39
Dupe of https://github.com/dropbox/pilot/issues/22

**Closed by wkiefer** 2017-03-07 17:40 UTC
Labels: duplicate

**Comment by aron** [comment] 2017-03-07 20:30
Oh man, I spent ages digging into that :)

**Comment by wkiefer** [comment] 2017-03-07 22:56
sorry! I blame timezones ; )
